### ISSUE TITLE
Affiliation History

### ISSUE THREAD

**Issue by alexeil** [julaudo/sikb-front#2]
### Description:
**As a** Anyone with rights on this club 
**I want** to be able to see all club affiliations (current and past)
**So that** I can check information of previous years

### Actual situation: 
We can only manage the current affiliation

### Target situation:
I want to be able to CRUD the current affiliation and read the previous affiliations.
I want a clear and smooth interface.
Before the first creation of affiliation the interface can be simple

### Acceptance criteria:
- [ ] I can read all the previous affiliations easily

**Comment by julaudo** [comment]
"clear and smooth interface", "simple interface" constraints should be targeted in all new features. Is there anything specific here?
