### ISSUE TITLE
Affiliate my club for the first time

### ISSUE THREAD

**Issue by alexeil** [julaudo/sikb-front#3]
### Description:
**As a** Club 
**I want** to affiliate to the FKBF my first year
**So that** enjoy this great federation 

### Actual situation: 
This is done by filling and sending a document to the federation (CF PJ)

### Target situation:
I want to be able to add all information required by the affiliation (CF Swagger)

When I go on my club page I have a button to affiliate.

I need to fill these information :
* prefectureNumber
* prefectureCity  
* siretNumber     
* address         
* postalCode      
* city            
* phoneNumber     
* email           
* webSite         
* board           
  * president     
  * presidentSex  
  * secretary     
  * secretarySex  
  * treasurer     
  * treasurerSex  
  * membersNumber 
  * electedDate   

### Acceptance criteria:
- [ ] I can create an affiliation for my club and my club only
- [ ] The affiliation is valid for the current season only (1 year)
- [ ] I can't create an affiliation if the club already has one for the current season
- [ ] After creation, the affiliations the club can "Save" the affiliation, so it's saved in "To complete" state, or "Submit" the affiliation, so it's saved in "Submitted" state.
- [ ] Submit is allowed only if all fields are filled.
- [ ] Save is always allowed

**Comment by julaudo** [comment]
As a first implementation, Submit is the only option, there is no "Save"
